spring:
  profiles:
    active: local

  config:
    import: datasource/application-h2.yml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

swagger:
  host: localhost:8080
  protocol: http

request:
  origins: http://localhost:3000,https://dev.gijol.im

---

spring:
  config:
    activate:
      on-profile: dev

swagger:
  host: dev-api.gijol.im
  protocol: https


request:
  origins: http://localhost:3000,http://localhost:3001,https://dev.gijol.im


---

spring:
  config:
    activate:
      on-profile: prod

swagger:
  host: api.gijol.im
  protocol: https


request:
  origins: https://gijol.im,https://dev.gijol.im