spring:
  profiles:
    active: local

  config:
    import: datasource/application-h2.yml

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  main:
    allow-bean-definition-overriding: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

swagger:
  host: localhost:8080
  protocol: http

request:
  origins: http://localhost:3000,https://dev.gijol.im, https://gijol-v2.vercel.app

management:
  endpoints:
    web:
      exposure:
        include: prometheus
    prometheus:
      enabled: true

clerk:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn1gLqfLMyt9pjnQ3DPDQrknwWw0HUNk8YYj+pPCGYDyswqtbsGKLD2weqjzwe6ffELrCbSN+UMVysSqAEgViIbnw6FG7Iyvs9WZTWXDxPscU8NE+JSITQsMLd0wkW9ZEzDTcSSumXu1Y8AW48W+Gf4IIDOICTqIKLPZBqcEGjK9Y2oyxJZYwLBqLB2SCWIhaahYk7/bt9s/ueG6ugoOn9fhXTl4U/5lE8sukXO1hQo6F5AChYVSEDCxX0vOqy0xRF1B7gDLIPbBccb+/od3h0qlsCPgKktxyfO0bq7GWjlgImuOmzFcVPR2d9W00p7z7dMqLdA9r2L/MPtLVbRsmeQIDAQAB

aes:
  key: "01234567890123456789012345678901"

internal:
  token:
    course: local-token

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
---

spring:
  config:
    activate:
      on-profile: dev
    import: datasource/application-docker-mysql.yml

swagger:
  host: dev.api.gijol.im
  protocol: https

internal:
  token:
    course: dev-token

request:
  origins: http://localhost:3000,http://localhost:3001,https://dev.gijol.im, https://gijol-v2.vercel.app,

---

spring:
  config:
    activate:
      on-profile: dev-db
    import: privates/application-db-dev.yml

swagger:
  host: dev.api.gijol.im
  protocol: https


request:
  origins: http://localhost:3000,http://localhost:3001,https://dev.gijol.im, https://gijol-v2.vercel.app,

---

spring:
  config:
    activate:
      on-profile: prod
    import: privates/application-db-prod.yml

swagger:
  host: api.gijol.im
  protocol: https

management:
  endpoints:
    web:
      exposure:
        include: prometheus
    prometheus:
      enabled: false

request:
  origins: https://gijol.im,https://dev.gijol.im, https://gijol-v2.vercel.app