spring:
  profiles:
    active: local

  config:
    import: datasource/application-h2.yml

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  main:
    allow-bean-definition-overriding: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

swagger:
  host: localhost:8080
  protocol: http

request:
  origins: http://localhost:3000,https://dev.gijol.im, https://gijol-v2.vercel.app

aes:
  key: "01234567890123456789012345678901"

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
---

spring:
  config:
    activate:
      on-profile: dev
    import: datasource/application-docker-mysql.yml

swagger:
  host: dev.api.gijol.im
  protocol: https


request:
  origins: http://localhost:3000,http://localhost:3001,https://dev.gijol.im, https://gijol-v2.vercel.app,


---

spring:
  config:
    activate:
      on-profile: prod
    import: privates/application-db-prod.yml

swagger:
  host: api.gijol.im
  protocol: https


request:
  origins: https://gijol.im,https://dev.gijol.im